In [ ]:
import tensorflow as tf
from tensorflow import keras 
from tensorflow.keras.preprocessing.text import one_hot
sent=['the glass is milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good machine learner',
      'your are a nice cricket bowler',]
print(sent)      

voc_size=10000
one_hot_repre=[one_hot(words,voc_size)for words in sent]
print(one_hot_repre)
from keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

sent_length=8

import numpy as np
embedded_docs=pad_sequences(one_hot_repre,padding='pre',maxlen=sent_length)
print(embedded_docs)
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

print(model.predict(embedded_docs)[0])
print(embedded_docs[0])


['the glass is milk', 'the glass of juice', 'the cup of tea', 'i am a good machine learner', 'your are a nice cricket bowler']
[[6940, 2953, 1605, 5485], [6940, 2953, 9120, 1636], [6940, 1489, 9120, 8890], [6404, 6772, 8239, 7, 3524, 5302], [315, 1708, 8239, 67, 2822, 3329]]
[[   0    0    0    0 6940 2953 1605 5485]
 [   0    0    0    0 6940 2953 9120 1636]
 [   0    0    0    0 6940 1489 9120 8890]
 [   0    0 6404 6772 8239    7 3524 5302]
 [   0    0  315 1708 8239   67 2822 3329]]
Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________
[[ 0.00496132 -0.01680318 -0.00643482  0.01897499  0.04199998 -0.00881403
   0.01424063 -0.00503904  0.00066435 -0.03854037]
 [ 0.00496132 -0.0168031